In [1]:
import numpy as np
import scipy.stats as sps
import matplotlib.pyplot as plt

# 1

# Генерация абсолютно случайной матрицы  𝑛×𝑚

In [3]:
def random_matrix(n, m):
    return sps.uniform.rvs(size=(n, m))

random_matrix(2, 3)

array([[0.41461345, 0.81688577, 0.8342401 ],
       [0.21933915, 0.38995517, 0.35531049]])

# Генерация случайной диагональной матрицы  𝑛×𝑛

In [5]:
def random_diag(n):
    return np.diag(sps.uniform.rvs(size=n))

random_diag(4)

array([[0.78195324, 0.        , 0.        , 0.        ],
       [0.        , 0.76661718, 0.        , 0.        ],
       [0.        , 0.        , 0.58054463, 0.        ],
       [0.        , 0.        , 0.        , 0.97510176]])

# Генерация случайной верхнетреугольной матрицы

In [8]:
def random_uptriangle(n):
    return np.triu(sps.uniform.rvs(size=n))

random_uptriangle(4)

array([[0.22655811, 0.62107095, 0.73048684, 0.15451416],
       [0.        , 0.62107095, 0.73048684, 0.15451416],
       [0.        , 0.        , 0.73048684, 0.15451416],
       [0.        , 0.        , 0.        , 0.15451416]])

# Генерация случайной нижнетреугольной матрицы

In [9]:
def random_downtriangle(n):
    return random_uptriangle(n).T

random_downtriangle(4)

array([[0.85348372, 0.        , 0.        , 0.        ],
       [0.08869281, 0.08869281, 0.        , 0.        ],
       [0.75027053, 0.75027053, 0.75027053, 0.        ],
       [0.68502912, 0.68502912, 0.68502912, 0.68502912]])

# Генерация симметричной матрицы

In [11]:
def random_sym(n):
    p = sps.uniform.rvs(size=(n ,n))
    return (p + p.T)/2

random_sym(4)

array([[0.19274048, 0.58244832, 0.41450469, 0.62912367],
       [0.58244832, 0.43519591, 0.85493316, 0.60088851],
       [0.41450469, 0.85493316, 0.86173629, 0.17206622],
       [0.62912367, 0.60088851, 0.17206622, 0.55619218]])

# Генерация вырожденной матрицы

In [197]:
def random_invert2x2(p):
    x = np.linalg.det(p)
    p[0][0] -= x/p[1][1]
    return p

print(random_invert2x2(p = sps.uniform.rvs(size=(2 ,2))))
print(np.linalg.det(p))

[[0.83178639 0.15434237]
 [0.88101102 0.16347626]]
3.6983579441361576e-17


In [200]:
def random_invert(n):
    p = sps.uniform.rvs(size=(n ,n))
    treck = []
    for i in range(n-1):
        for j in range(n-1):
            treck.append(p[n-2-i:n-i, n-2-j:n-j])
            random_invert2x2(treck[j+i])
    return p

l = random_invert(4)
print(l, np.linalg.det(l))

# как же у меня сгорел мозг после этого...

[[0.44783989 0.29370406 0.24297333 0.55574087]
 [0.24713824 0.0819038  0.4924657  0.13300428]
 [0.86826794 0.28729579 1.7274329  0.46654209]
 [0.44411203 0.14694948 0.88356796 0.23863251]] 3.4674369073667055e-21
