In [1]:
import numpy as np
import scipy.stats as sps
import matplotlib.pyplot as plt

# 1

# Генерация абсолютно случайной матрицы  𝑛×𝑚

In [3]:
def random_matrix(n, m):
    return sps.uniform.rvs(size=(n, m))

random_matrix(2, 3)

array([[0.41461345, 0.81688577, 0.8342401 ],
       [0.21933915, 0.38995517, 0.35531049]])

# Генерация случайной диагональной матрицы  𝑛×𝑛

In [5]:
def random_diag(n):
    return np.diag(sps.uniform.rvs(size=n))

random_diag(4)

array([[0.78195324, 0.        , 0.        , 0.        ],
       [0.        , 0.76661718, 0.        , 0.        ],
       [0.        , 0.        , 0.58054463, 0.        ],
       [0.        , 0.        , 0.        , 0.97510176]])

# Генерация случайной верхнетреугольной матрицы

In [8]:
def random_uptriangle(n):
    return np.triu(sps.uniform.rvs(size=n))

random_uptriangle(4)

array([[0.22655811, 0.62107095, 0.73048684, 0.15451416],
       [0.        , 0.62107095, 0.73048684, 0.15451416],
       [0.        , 0.        , 0.73048684, 0.15451416],
       [0.        , 0.        , 0.        , 0.15451416]])

# Генерация случайной нижнетреугольной матрицы

In [9]:
def random_downtriangle(n):
    return random_uptriangle(n).T

random_downtriangle(4)

array([[0.85348372, 0.        , 0.        , 0.        ],
       [0.08869281, 0.08869281, 0.        , 0.        ],
       [0.75027053, 0.75027053, 0.75027053, 0.        ],
       [0.68502912, 0.68502912, 0.68502912, 0.68502912]])

# Генерация симметричной матрицы

In [11]:
def random_sym(n):
    p = sps.uniform.rvs(size=(n ,n))
    return (p + p.T)/2

random_sym(4)

array([[0.19274048, 0.58244832, 0.41450469, 0.62912367],
       [0.58244832, 0.43519591, 0.85493316, 0.60088851],
       [0.41450469, 0.85493316, 0.86173629, 0.17206622],
       [0.62912367, 0.60088851, 0.17206622, 0.55619218]])

# Генерация вырожденной матрицы

In [197]:
def random_invert2x2(p):
    x = np.linalg.det(p)
    p[0][0] -= x/p[1][1]
    return p

print(random_invert2x2(p = sps.uniform.rvs(size=(2 ,2))))
print(np.linalg.det(p))

[[0.83178639 0.15434237]
 [0.88101102 0.16347626]]
3.6983579441361576e-17


In [207]:
def random_invert(n):
    p = sps.uniform.rvs(size=(n ,n))
    treck = []
    for i in range(n-1):
        for j in range(n-1):
            treck.append(p[n-2-i:n-i, n-2-j:n-j])
            random_invert2x2(treck[j+i])
    return p

l = random_invert(4)
print(l, np.linalg.det(l))

# как же у меня сгорел мозг после этого...

[[0.09085939 0.77489394 0.16531145 0.5904861 ]
 [0.50126305 0.46167181 0.86915866 0.77978552]
 [0.06274243 0.22206201 0.41806131 0.37507324]
 [0.11044321 0.39088765 0.73589805 0.66022772]] 0.0


# Генерация матрицы ступенчатого вида  𝑛×𝑛 ранга m

In [236]:
def random_stupen(n, m):
    p = np.triu(sps.uniform.rvs(size=n))
    b = np.concatenate(( np.zeros((m, n)), np.ones((n-m, n)) ), axis=0)
    p[b==1] = 0
    return p

random_stupen(4, 2)
    

array([[0.74860706, 0.41271509, 0.96131353, 0.84364778],
       [0.        , 0.41271509, 0.96131353, 0.84364778],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

# Генерация возмущения матрицы  𝑛×𝑚
n
×
m
 , каждый элемент которой не превосходит по модулю заданный  𝜀
ε
 

# 2

Воспользуемся иллюстрацией визуализации норм. Итоговая картинка будет выглядеть как ромб, с вписанной и описанной окружностью.
$$C_{1} || x || _{2} \leq || x || _{1}  \leq C_{2} || x || _{2}  \Rightarrow \newline$$
$$|| x || _{2} \leq || x || _{1} \leq \sqrt{2} || x || _{2} $$

# 3

$$ || x || _{\infty}  = max \, x_{i} \newline$$
$$ || x || _{2} = \sqrt{\sum_{i} x_{i}^{2}} \leq \sqrt{m \, max \, (x_{i})^{2}} = \sqrt{m} \, max \, |x_{i}|$$
Соответственно, получаем:
$$ || x || _{2} \leq \sqrt{m} \, || x || _{\infty} $$

Для численного примера, можем взять единичный вектор размерности $n$, тогда
$$\newline || x || _{\infty} = 1 , || x || _{2} = \sqrt{m} \Rightarrow || x|| _{2} = \sqrt{m} || x || _{\infty} \newline$$
$$ \dfrac{||A x||_{2}}{||x||_{2}} \geq \dfrac{|| A x || _{2}}{\sqrt{n} || x||_{\infty}} \geq \dfrac{|| A x|| _{\infty}}{\sqrt{n} ||x ||_{\infty}} \Rightarrow || A||_{\infty} \leq \sqrt{n} || A||_{2}$$